# Generated by Django 6.1 on 2026-10-05 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('account', 'Account update'), ('property', 'Property assignment'), ('inquiry', 'Inquiry update'), ('application', 'Application update'), ('rent_change', 'Rent change'), ('maintenance', 'Maintenance update'), ('invoice', 'Rent invoice'), ('payment', 'Payment update'), ('lease', 'Lease update')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=280)),
                ('destination', models.CharField(choices=[('admin.users', 'Admin user accounts'), ('owner.approvals', 'Owner application approvals'), ('owner.pricing', 'Owner rent changes'), ('owner.maintenance', 'Owner maintenance'), ('owner.billing', 'Owner payments'), ('owner.contracts', 'Owner leases'), ('manager.properties', 'Manager properties'), ('manager.inquiries', 'Manager inquiries'), ('manager.applications', 'Manager applications'), ('manager.pricing', 'Manager rent changes'), ('manager.maintenance', 'Manager maintenance'), ('manager.billing', 'Manager rent ledger'), ('manager.contracts', 'Manager leases'), ('agent.listings', 'Agent listings'), ('agent.inquiries', 'Agent inquiries'), ('agent.applications', 'Agent applications'), ('tenant.payments', 'Tenant payments'), ('tenant.lease', 'Tenant lease'), ('tenant.maintenance', 'Tenant maintenance')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notif_user_read_date_idx'), models.Index(fields=['recipient', '-created_at'], name='notif_user_date_idx')],
            },
        ),
    ]
