# Generated by Django 6.1 on 2026-10-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='destination',
            field=models.CharField(choices=[('admin.overview', 'Admin overview'), ('admin.users', 'Admin user accounts'), ('owner.overview', 'Owner overview'), ('owner.approvals', 'Owner application approvals'), ('owner.pricing', 'Owner rent changes'), ('owner.maintenance', 'Owner maintenance'), ('owner.billing', 'Owner payments'), ('owner.contracts', 'Owner leases'), ('manager.overview', 'Manager overview'), ('manager.properties', 'Manager properties'), ('manager.inquiries', 'Manager inquiries'), ('manager.applications', 'Manager applications'), ('manager.pricing', 'Manager rent changes'), ('manager.maintenance', 'Manager maintenance'), ('manager.billing', 'Manager rent ledger'), ('manager.contracts', 'Manager leases'), ('agent.overview', 'Agent overview'), ('agent.listings', 'Agent listings'), ('agent.inquiries', 'Agent inquiries'), ('agent.applications', 'Agent applications'), ('tenant.overview', 'Tenant overview'), ('tenant.payments', 'Tenant payments'), ('tenant.lease', 'Tenant lease'), ('tenant.maintenance', 'Tenant maintenance')], max_length=32),
        ),
    ]
